version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: merchant-agent
      runtime: docker
      repo: https://github.com/susancagle80-debug/x402-merchant-agent
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeploy: true
