version: "1"
projects:
- name: x402-merchant-agent
  environments:
  - name: Production
    services:
    - type: web
      name: merchant-agent
      runtime: docker
      repo: https://github.com/gamezcagle95-dev/x402-merchant-agent
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeploy: true
      envVars: []
